# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Klaus Lex
title: Loves Dogs & Robots
# email: klaus@klauslex.com
website: www.klauslex.com

# Social links
twitter_username: klaus_lex
github_username:  klauslex
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: klauslex
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Additional icon links
# additional_links:
# - title: Medium
#   icon: fab fa-medium
#   url: https://medium.com/@klaus_lex
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

medium_username: klaus_lex

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Klaus - Vienna-based engineer & robotics student.<br>
  
  During my studies I've been using mostly <mark>MATLAB</mark> but also some <mark>Python</mark>, <mark>C++</mark> & <mark>ROS</mark>.<br>
  The most interesting areas for me so far were related to <mark>SLAM</mark>.<br>
  I have experience working in project management, engineering and software development.<br>
  This includes working with industrial robots such as <mark>ABB</mark>, <mark>KUKA</mark> & <mark>Universal Robots</mark>, as well as working with various SoC or µCs, like a <mark>Raspberry Pi</mark>, <mark>NVIDIA Jetson</mark>, <mark>Arduino</mark> & <mark>OpenCR</mark>, as well as sensors and cameras of different brands like <mark>Cognex</mark>, <mark>Basler</mark>, <mark>ydLidar</mark>.<br>
  
  <br>
  <mark>I'm actively looking for a position as a phd student to work on autonomous mobile robots in the wild starting in 2023.</mark><br>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  
  Currently I also explore options in Scientific Communication and joined the <mark>Pint of Science Austria</mark> as event manager and moderator.

  The little time I have left spend on a mixture of:
   - Photography  
   - 3D printing (Elegoo Mars Pro)
   - 3D-Modelling in my favorite modeller <mark>BLENDER</mark>
   - Image editing in <mark>Affinity Suite</mark> and <mark>Adobe Lightroom</mark> as well as
   - Video editing in <mark>Vegas</mark> and <mark>Final Cut</mark>



# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
