# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Klaus Lex
title: Engineer by Trade - Roboticist at Heart
# email: klaus@klauslex.com
website: www.klauslex.com

# Social links
twitter_username: klaus_lex
github_username:  klauslex
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: klauslex
linkedin_username: klauslex
# pinterest_username: jekyll
youtube_username: klauslex
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Klaus and I love <mark>#robotics</mark>.

  I have a background in <mark>#mechanical engineering</mark> and currently pursue a masters in <mark>#robotics and automation</mark>.<br>
  During my studies I learned a lot in the fields of <mark>#manufacturing </mark> and <mark>#project management</mark>.<br>
  Besides practical skills I had the chance to improve my <mark>#teanworking</mark> skills and took charge of <mark>#leadership</mark> for some projects.
  
  Now I'm looking for chances to expand my skills in <mark>#programming</mark> which I still need a lot of practice in.<br>
  In the meantime I take several <mark>#MOOC</mark> and spend too much time on <mark>#Twitter</mark>

  

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in <mark>#robotics</mark> some of my other interests and hobbies are:
   - <mark>#3D printing </mark> (FDM & MSLA)
   - <mark>#3D modelling </mark> (I LOVE <mark>#Blender</mark> but haven't had the time to spend on since well before they updated the GUI)
   - <mark>#Photography</mark> & <mark>#videography</mark> are things I rarely use to learn more about editing software
   - <mark>#Programming</mark> is what I probably lack the most currently and should focus on

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
