# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Klaus Lex
title: Engineer by Trade - Roboticist at Heart
# email: klaus@klauslex.com
website: www.klauslex.com

# Social links
twitter_username: klaus_lex
github_username:  klauslex
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: klauslex
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Additional icon links
# additional_links:
# - title: Medium
#   icon: fab fa-medium
#   url: https://medium.com/@klaus_lex
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

medium_username: klaus_lex

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Klaus. I'm an engineer based in <mark>Vienna, Austria</mark> and look to transition into <mark>#robotics research</mark>.

  I have a background in <mark>#mechanical engineering</mark> and currently study <mark>Robotics</mark> at <mark>University West</mark> in Sweden.<br>
  Working in the fields of <mark>#manufacturing</mark> and <mark>#project management</mark> during my studies gave me the chance me learn a lot and improved my <mark>#teamworking</mark> skills while also learning some <mark>#leadership</mark>.
  
  During my studies I've been using mostly <mark>MATLAB</mark> but also some <mark>Python</mark> and <mark>ROS</mark>.<br>
  The most interesting areas for me so far were related to <mark>perception</mark> and <mark>navigation</mark>.<br>
  In the meantime I'm taking several <mark>MOOCs</mark> and spend way too much time on <mark>Twitter</mark>.

  

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in <mark>#robotics</mark> some of my other interests and hobbies are:
   - 3D printing with FDM and MSLA
   - 3D modelling in <mark>#Blender</mark> and <mark>Fusion360</mark>
   - Image/Video editing in <mark>Affinity Suite</mark> and <mark>Vegas</mark>



# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
